### PR TITLE
Add embedchain + chainlit integration to docs

### PR DESCRIPTION
**Pull request by sidmohanty11**
Hello everyone! I'm part of the DevRel team here at [Embedchain](https://github.com/embedchain/embedchain), and we're huge fans of Chainlit. Our team is excited to demonstrate the seamless integration between Chainlit and Embedchain. Our upcoming [chainlit integration](https://github.com/embedchain/embedchain/pull/1020) will illustrate how users can effortlessly create chatbots using just a single command through this integration. Would love to collaborate on this! Thanks!

cc @deshraj @taranjeet

### CODE REVIEW

**Review by willydouhard — APPROVED** [review]
Awesome, don't hesitate to ping us on discord so we can schedule a call!

**Comment by taranjeet** [comment]
thanks @willydouhard for reviewing and merging this so quickly.
❤️  from @embedchain team

**Comment by willydouhard** [comment]
Hello @taranjeet, thank you for this PR! Wish you and Embedchain all the best for 2024!

Will merge this PR, in the mean time @constantinidan will contact you to see how we can enhance this integration.

**Comment by taranjeet** [comment]
thank you @willydouhard .

**Pull request merged**
