### PR TITLE
Update oauth.mdx

### PR DESCRIPTION
**Pull request by rahul-newtuple**
Note for .env file in which we can place the oauth environment variables

### CODE REVIEW

**Comment by rahul-newtuple** [comment]
This will guide the users on how to add the env file which Chainlit can load, there is a separate section for adding env vars but users may miss that out, leading to confusion

**Review by willydouhard — APPROVED** [review]
thank you!

**Comment by rahul-newtuple** [comment]
Thanks for the merge !

**Review by dhirajnewtuple — COMMENTED** [review]
Minor changes...

**Pull request merged**
